const SS_ID = '1lrgeU_WymEdhSi7P0uOyH5BUpvTD7xt1SqVYW1Gpmp4';
const TZ = Session.getScriptTimeZone() || 'Asia/Kolkata';
const SHEETS = {
  Users:['id','name','username','passwordHash','role','active','createdAt'],
  Products:['id','sku','barcode','name','category','brand','unit','hsn','gst','purchaseRate','rate','mrp','stock','reorder','batch','expiry','active','createdAt'],
  Customers:['id','name','phone','village','gstin','credit','creditLimit','active','createdAt'],
  Suppliers:['id','name','phone','gstin','address','payable','active','createdAt'],
  Sales:['id','invoice','date','time','customerId','customer','payment','subtotal','tax','total','createdBy','createdAt'],
  SaleItems:['id','saleId','productId','sku','name','qty','rate','gst','tax','lineTotal'],
  Purchases:['id','invoice','date','supplierId','supplier','payment','subtotal','tax','total','createdBy','createdAt'],
  PurchaseItems:['id','purchaseId','productId','sku','name','qty','rate','gst','tax','lineTotal'],
  SalesReturns:['id','returnNo','date','saleId','invoice','customerId','customer','refundMode','subtotal','tax','total','createdBy','createdAt'],
  SalesReturnItems:['id','returnId','saleItemId','productId','sku','name','qty','rate','gst','tax','lineTotal'],
  PurchaseReturns:['id','returnNo','date','purchaseId','invoice','supplierId','supplier','paymentMode','subtotal','tax','total','createdBy','createdAt'],
  PurchaseReturnItems:['id','returnId','purchaseItemId','productId','sku','name','qty','rate','gst','tax','lineTotal'],
  Payments:['id','date','type','partyId','party','mode','reference','amount','notes','createdBy','createdAt'],
  StockAdjustments:['id','date','productId','sku','product','type','qty','reason','reference','createdBy','createdAt'],
  Expenses:['id','date','category','description','payment','amount','createdBy','createdAt'],
  Settings:['key','value'],
  AuditLog:['id','timestamp','username','role','action','entity','entityId','details']
};

function doGet(){return HtmlService.createTemplateFromFile('index').evaluate().setTitle('Shivsagar Krushi Seva Kendra & Hardware').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function setupDatabase(){
  if(SS_ID==='PASTE_YOUR_GOOGLE_SHEET_ID_HERE') throw new Error('Set SS_ID in Code.gs before deployment.');
  const ss=SpreadsheetApp.openById(SS_ID);
  Object.keys(SHEETS).forEach(n=>{let sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(SHEETS[n]);else{const h=sh.getRange(1,1,1,SHEETS[n].length).getValues()[0];if(h.join('|')!==SHEETS[n].join('|')){sh.clear();sh.appendRow(SHEETS[n])}}sh.setFrozenRows(1);sh.getRange(1,1,1,SHEETS[n].length).setFontWeight('bold')});
  if(!getRows('Settings').length)[['shopName','Shivsagar Krushi Seva Kendra & Hardware'],['address',''],['phone',''],['whatsapp',''],['email',''],['gstin',''],['invoicePrefix','SSK'],['currency','INR']].forEach(x=>appendRow('Settings',{key:x[0],value:x[1]}));
  if(!getRows('Users').length)appendRow('Users',{id:uid(),name:'Owner / Administrator',username:'admin',passwordHash:hash_('admin123'),role:'Administrator',active:true,createdAt:now_()});
  return {ok:true};
}
function api(action,p){try{setupDatabase();p=p||{};switch(action){
case'login':return login_(p);case'bootstrap':return bootstrap_(p);case'saveProduct':return saveProduct_(p);case'deleteProduct':return deleteById_('Products',p.id,p.token);case'saveCustomer':return saveCustomer_(p);case'saveSupplier':return saveSupplier_(p);case'saveExpense':return saveExpense_(p);case'saveUser':return saveUser_(p);case'toggleUser':return toggleUser_(p);case'saveSettings':return saveSettings_(p);case'createSale':return createSale_(p);case'createPurchase':return createPurchase_(p);case'saleReturn':return saleReturn_(p);case'purchaseReturn':return purchaseReturn_(p);case'recordPayment':return recordPayment_(p);case'stockAdjust':return stockAdjust_(p);case'reports':return reports_();case'ledger':return ledger_(p);case'gstReport':return gstReport_(p);case'exportData':return exportData_(p);case'clearBusinessData':return clearBusinessData_(p);case'invoicePdf':return invoicePdf_(p);case'receiptPdf':return receiptPdf_(p);default:throw new Error('Unknown action: '+action)}}catch(e){return{ok:false,error:e.message}}}
function login_(p){const u=getRows('Users').find(x=>String(x.username).toLowerCase()===String(p.username||'').toLowerCase()&&String(x.active)==='true');if(!u||u.passwordHash!==hash_(String(p.password||'')))return{ok:false,error:'Invalid username or password.'};const t=Utilities.getUuid();CacheService.getScriptCache().put('AUTH_'+t,JSON.stringify({username:u.username,name:u.name,role:u.role}),21600);audit_(u,'LOGIN','Auth','','Successful login');return{ok:true,token:t,user:{name:u.name,username:u.username,role:u.role}}}
function auth_(t){const s=CacheService.getScriptCache().get('AUTH_'+t);if(!s)throw new Error('Session expired. Please login again.');return JSON.parse(s)}
function bootstrap_(p){const u=auth_(p.token);return{ok:true,user:u,settings:settings_(),products:getRows('Products').filter(x=>String(x.active)!=='false'),customers:getRows('Customers').filter(x=>String(x.active)!=='false'),suppliers:getRows('Suppliers').filter(x=>String(x.active)!=='false'),users:getRows('Users'),sales:getRows('Sales'),saleItems:getRows('SaleItems'),purchases:getRows('Purchases'),purchaseItems:getRows('PurchaseItems'),salesReturns:getRows('SalesReturns'),purchaseReturns:getRows('PurchaseReturns'),payments:getRows('Payments'),adjustments:getRows('StockAdjustments'),expenses:getRows('Expenses')}}
function saveProduct_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Inventory Staff']);const o=p.data;o.id=o.id||uid();o.active=true;o.createdAt=o.createdAt||now_();upsert_('Products',o);audit_(u,'SAVE','Product',o.id,o.name);return{ok:true}}
function saveCustomer_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Billing Staff']);const o=p.data;o.id=o.id||uid();o.active=true;o.createdAt=o.createdAt||now_();o.credit=Number(o.credit||0);o.creditLimit=Number(o.creditLimit||0);upsert_('Customers',o);return{ok:true}}
function saveSupplier_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Inventory Staff']);const o=p.data;o.id=o.id||uid();o.active=true;o.createdAt=o.createdAt||now_();o.payable=Number(o.payable||0);upsert_('Suppliers',o);return{ok:true}}
function saveExpense_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager']);const o=p.data;o.id=uid();o.createdBy=u.username;o.createdAt=now_();appendRow('Expenses',o);audit_(u,'CREATE','Expense',o.id,o.description);return{ok:true}}
function saveUser_(p){const u=auth_(p.token);requireRole_(u,['Administrator']);const d=p.data;if(!d.username||!d.password)throw new Error('Username and password required.');if(getRows('Users').some(x=>String(x.username).toLowerCase()===String(d.username).toLowerCase()))throw new Error('Username already exists.');appendRow('Users',{id:uid(),name:d.name,username:d.username,passwordHash:hash_(d.password),role:d.role,active:true,createdAt:now_()});return{ok:true}}
function toggleUser_(p){const u=auth_(p.token);requireRole_(u,['Administrator']);const x=getRows('Users').find(x=>String(x.id)===String(p.id));if(!x)throw new Error('User not found.');x.active=String(x.active)==='true'?'false':'true';upsert_('Users',x);return{ok:true}}
function saveSettings_(p){const u=auth_(p.token);requireRole_(u,['Administrator']);Object.keys(p.settings||{}).forEach(k=>upsert_('Settings',{key:k,value:String(p.settings[k])}));return{ok:true}}
function createSale_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Billing Staff']);if(!p.items?.length)throw new Error('No bill items.');const cust=getRows('Customers').find(x=>String(x.id)===String(p.customerId));if(!cust)throw new Error('Customer not found.');const products=getRows('Products');let sub=0,tax=0,lines=[];p.items.forEach(it=>{const prod=products.find(x=>String(x.id)===String(it.productId));if(!prod)throw new Error('Product not found.');const q=Number(it.qty),r=Number(prod.rate),g=Number(prod.gst||0);if(q<=0||Number(prod.stock)<q)throw new Error('Insufficient stock: '+prod.name);const l=q*r,t=l*g/100;sub+=l;tax+=t;prod.stock=Number(prod.stock)-q;upsert_('Products',prod);lines.push({id:uid(),productId:prod.id,sku:prod.sku,name:prod.name,qty:q,rate:r,gst:g,tax:t,lineTotal:l+t})});const sale={id:uid(),invoice:invoiceNo_(),date:date_(),time:time_(),customerId:cust.id,customer:cust.name,payment:p.payment||'Cash',subtotal:sub,tax,total:sub+tax,createdBy:u.username,createdAt:now_()};appendRow('Sales',sale);lines.forEach(x=>{x.saleId=sale.id;appendRow('SaleItems',x)});if(sale.payment==='Credit'){cust.credit=Number(cust.credit||0)+sale.total;upsert_('Customers',cust)}audit_(u,'CREATE','Sale',sale.id,sale.invoice);return{ok:true,sale,items:lines}}
function createPurchase_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Inventory Staff']);if(!p.items?.length)throw new Error('No purchase items.');const sup=getRows('Suppliers').find(x=>String(x.id)===String(p.supplierId));if(!sup)throw new Error('Supplier not found.');const products=getRows('Products');let sub=0,tax=0,lines=[];p.items.forEach(it=>{const prod=products.find(x=>String(x.id)===String(it.productId));if(!prod)throw new Error('Product not found.');const q=Number(it.qty),r=Number(it.rate),g=Number(it.gst||0),l=q*r,t=l*g/100;sub+=l;tax+=t;prod.stock=Number(prod.stock)+q;prod.purchaseRate=r;upsert_('Products',prod);lines.push({id:uid(),productId:prod.id,sku:prod.sku,name:prod.name,qty:q,rate:r,gst:g,tax:t,lineTotal:l+t})});const pur={id:uid(),invoice:p.invoice||purchaseNo_(),date:p.date||date_(),supplierId:sup.id,supplier:sup.name,payment:p.payment||'Credit',subtotal:sub,tax,total:sub+tax,createdBy:u.username,createdAt:now_()};appendRow('Purchases',pur);lines.forEach(x=>{x.purchaseId=pur.id;appendRow('PurchaseItems',x)});if(pur.payment==='Credit'){sup.payable=Number(sup.payable||0)+pur.total;upsert_('Suppliers',sup)}audit_(u,'CREATE','Purchase',pur.id,pur.invoice);return{ok:true,purchase:pur,items:lines}}
function saleReturn_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Billing Staff']);const sale=getRows('Sales').find(x=>String(x.id)===String(p.saleId));if(!sale)throw new Error('Sale not found.');const orig=getRows('SaleItems').filter(x=>String(x.saleId)===String(sale.id));if(!p.items?.length)throw new Error('Select return items.');const products=getRows('Products');let sub=0,tax=0,lines=[];p.items.forEach(it=>{const oi=orig.find(x=>String(x.id)===String(it.saleItemId));if(!oi)throw new Error('Sale item not found.');const q=Number(it.qty),max=Number(oi.qty);if(q<=0||q>max)throw new Error('Invalid return quantity for '+oi.name);const g=Number(oi.gst||0),l=q*Number(oi.rate),t=l*g/100;sub+=l;tax+=t;const prod=products.find(x=>String(x.id)===String(oi.productId));prod.stock=Number(prod.stock)+q;upsert_('Products',prod);lines.push({id:uid(),saleItemId:oi.id,productId:oi.productId,sku:oi.sku,name:oi.name,qty:q,rate:oi.rate,gst:g,tax:t,lineTotal:l+t})});const ret={id:uid(),returnNo:'SR-'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd-HHmmss'),date:date_(),saleId:sale.id,invoice:sale.invoice,customerId:sale.customerId,customer:sale.customer,refundMode:p.refundMode||'Credit',subtotal:sub,tax,total:sub+tax,createdBy:u.username,createdAt:now_()};appendRow('SalesReturns',ret);lines.forEach(x=>{x.returnId=ret.id;appendRow('SalesReturnItems',x)});const cust=getRows('Customers').find(x=>String(x.id)===String(sale.customerId));if(cust){if(sale.payment==='Credit'||ret.refundMode==='Credit'){cust.credit=Math.max(0,Number(cust.credit||0)-ret.total);upsert_('Customers',cust)}}audit_(u,'RETURN','Sale',sale.id,ret.returnNo);return{ok:true,return:ret}}
function purchaseReturn_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Inventory Staff']);const pur=getRows('Purchases').find(x=>String(x.id)===String(p.purchaseId));if(!pur)throw new Error('Purchase not found.');const orig=getRows('PurchaseItems').filter(x=>String(x.purchaseId)===String(pur.id));const products=getRows('Products');let sub=0,tax=0,lines=[];p.items.forEach(it=>{const oi=orig.find(x=>String(x.id)===String(it.purchaseItemId));if(!oi)throw new Error('Purchase item not found.');const q=Number(it.qty);if(q<=0||q>Number(oi.qty))throw new Error('Invalid return quantity.');const prod=products.find(x=>String(x.id)===String(oi.productId));if(Number(prod.stock)<q)throw new Error('Insufficient stock to return '+prod.name);const l=q*Number(oi.rate),t=l*Number(oi.gst||0)/100;sub+=l;tax+=t;prod.stock=Number(prod.stock)-q;upsert_('Products',prod);lines.push({id:uid(),purchaseItemId:oi.id,productId:oi.productId,sku:oi.sku,name:oi.name,qty:q,rate:oi.rate,gst:oi.gst,tax:t,lineTotal:l+t})});const ret={id:uid(),returnNo:'PR-'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd-HHmmss'),date:date_(),purchaseId:pur.id,invoice:pur.invoice,supplierId:pur.supplierId,supplier:pur.supplier,paymentMode:p.paymentMode||'Credit',subtotal:sub,tax,total:sub+tax,createdBy:u.username,createdAt:now_()};appendRow('PurchaseReturns',ret);lines.forEach(x=>{x.returnId=ret.id;appendRow('PurchaseReturnItems',x)});const sup=getRows('Suppliers').find(x=>String(x.id)===String(pur.supplierId));if(sup&&pur.payment==='Credit'){sup.payable=Math.max(0,Number(sup.payable||0)-ret.total);upsert_('Suppliers',sup)}return{ok:true,return:ret}}
function recordPayment_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Billing Staff']);const amt=Number(p.amount);if(amt<=0)throw new Error('Amount must be positive.');if(p.type==='Customer'){const c=getRows('Customers').find(x=>String(x.id)===String(p.partyId));if(!c)throw new Error('Customer not found.');c.credit=Math.max(0,Number(c.credit||0)-amt);upsert_('Customers',c)}else{requireRole_(u,['Administrator','Manager','Inventory Staff']);const s=getRows('Suppliers').find(x=>String(x.id)===String(p.partyId));if(!s)throw new Error('Supplier not found.');s.payable=Math.max(0,Number(s.payable||0)-amt);upsert_('Suppliers',s)}const o={id:uid(),date:p.date||date_(),type:p.type,partyId:p.partyId,party:p.party,mode:p.mode||'Cash',reference:p.reference||'',amount:amt,notes:p.notes||'',createdBy:u.username,createdAt:now_()};appendRow('Payments',o);return{ok:true}}
function stockAdjust_(p){const u=auth_(p.token);requireRole_(u,['Administrator','Manager','Inventory Staff']);const prod=getRows('Products').find(x=>String(x.id)===String(p.productId));if(!prod)throw new Error('Product not found.');const q=Number(p.qty);if(q<=0)throw new Error('Quantity must be positive.');if(p.type==='OUT'&&Number(prod.stock)<q)throw new Error('Insufficient stock.');prod.stock=Number(prod.stock)+(p.type==='IN'?q:-q);upsert_('Products',prod);appendRow('StockAdjustments',{id:uid(),date:p.date||date_(),productId:prod.id,sku:prod.sku,product:prod.name,type:p.type,qty:q,reason:p.reason||'',reference:p.reference||'',createdBy:u.username,createdAt:now_()});return{ok:true}}
function reports_(){const products=getRows('Products'),sales=getRows('Sales'),purchases=getRows('Purchases'),expenses=getRows('Expenses'),customers=getRows('Customers'),suppliers=getRows('Suppliers'),sr=getRows('SalesReturns'),pr=getRows('PurchaseReturns');return{products,sales,purchases,expenses,customers,suppliers,salesReturns:sr,purchaseReturns:pr,summary:{sales:sum_(sales,'total'),purchases:sum_(purchases,'total'),expenses:sum_(expenses,'amount'),stock:products.reduce((a,x)=>a+Number(x.stock||0)*Number(x.purchaseRate||x.rate||0),0),credit:sum_(customers,'credit'),payable:sum_(suppliers,'payable'),salesReturns:sum_(sr,'total'),purchaseReturns:sum_(pr,'total')}}}
function ledger_(p){auth_(p.token);if(p.type==='Customer'){const c=getRows('Customers').find(x=>String(x.id)===String(p.id));const sales=getRows('Sales').filter(x=>String(x.customerId)===String(p.id)),payments=getRows('Payments').filter(x=>x.type==='Customer'&&String(x.partyId)===String(p.id)),returns=getRows('SalesReturns').filter(x=>String(x.customerId)===String(p.id));return{party:c,transactions:[...sales.map(x=>({date:x.date,kind:'Sale',ref:x.invoice,debit:x.total,credit:0})),...returns.map(x=>({date:x.date,kind:'Sales Return',ref:x.returnNo,debit:0,credit:x.total})),...payments.map(x=>({date:x.date,kind:'Payment',ref:x.reference||x.id,debit:0,credit:x.amount}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)))}}const s=getRows('Suppliers').find(x=>String(x.id)===String(p.id));const pur=getRows('Purchases').filter(x=>String(x.supplierId)===String(p.id)),payments=getRows('Payments').filter(x=>x.type==='Supplier'&&String(x.partyId)===String(p.id)),returns=getRows('PurchaseReturns').filter(x=>String(x.supplierId)===String(p.id));return{party:s,transactions:[...pur.map(x=>({date:x.date,kind:'Purchase',ref:x.invoice,debit:x.total,credit:0})),...returns.map(x=>({date:x.date,kind:'Purchase Return',ref:x.returnNo,debit:0,credit:x.total})),...payments.map(x=>({date:x.date,kind:'Payment',ref:x.reference||x.id,debit:0,credit:x.amount}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)))} }
function gstReport_(p){auth_(p.token);const sales=getRows('Sales'),purchases=getRows('Purchases'),sr=getRows('SalesReturns'),pr=getRows('PurchaseReturns');const by=(arr)=>{const m={};arr.forEach(x=>{const g=Number(x.gst||0);m[g]=(m[g]||0)+Number(x.tax||0)});return m};return{output:by(getRows('SaleItems')),input:by(getRows('PurchaseItems')),salesReturns:sum_(sr,'tax'),purchaseReturns:sum_(pr,'tax'),salesTotal:sum_(sales,'total'),purchaseTotal:sum_(purchases,'total')}}
function exportData_(p){const u=auth_(p.token);requireRole_(u,['Administrator']);const out={};Object.keys(SHEETS).forEach(n=>out[n]=getRows(n));return{ok:true,json:JSON.stringify(out)}}
function clearBusinessData_(p){const u=auth_(p.token);requireRole_(u,['Administrator']);['Products','Customers','Suppliers','Sales','SaleItems','Purchases','PurchaseItems','SalesReturns','SalesReturnItems','PurchaseReturns','PurchaseReturnItems','Payments','StockAdjustments','Expenses','AuditLog'].forEach(n=>{const sh=sheet_(n);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).clearContent()});return{ok:true}}
function invoicePdf_(p){const u=auth_(p.token);const sale=getRows('Sales').find(x=>String(x.id)===String(p.saleId));if(!sale)throw new Error('Invoice not found.');const items=getRows('SaleItems').filter(x=>String(x.saleId)===String(sale.id));return pdfBlob_('Invoice '+sale.invoice,invoiceHtml_(sale,items,settings_()))}
function receiptPdf_(p){const u=auth_(p.token);const pay=getRows('Payments').find(x=>String(x.id)===String(p.paymentId));if(!pay)throw new Error('Receipt not found.');return pdfBlob_('Payment Receipt',receiptHtml_(pay,settings_()))}
function pdfBlob_(name,html){const b=Utilities.newBlob(html,'text/html',name+'.html').getAs('application/pdf');return{ok:true,name:name+'.pdf',mime:'application/pdf',base64:Utilities.base64Encode(b.getBytes())}}
function invoiceHtml_(s,items,set){return`<html><body style="font-family:Arial;padding:28px"><h2>${esc_(set.shopName)}</h2><p>${esc_(set.address)}<br>Phone: ${esc_(set.phone)} | GSTIN: ${esc_(set.gstin)}</p><hr><h3>Tax Invoice: ${esc_(s.invoice)}</h3><p>Date: ${esc_(s.date)} | Customer: ${esc_(s.customer)} | Payment: ${esc_(s.payment)}</p><table width="100%" border="1" cellspacing="0" cellpadding="6"><tr><th>Item</th><th>Qty</th><th>Rate</th><th>GST</th><th>Total</th></tr>${items.map(i=>`<tr><td>${esc_(i.name)}</td><td>${i.qty}</td><td>${i.rate}</td><td>${i.gst}%</td><td>${i.lineTotal}</td></tr>`).join('')}</table><h3 style="text-align:right">Subtotal: ${s.subtotal}<br>Tax: ${s.tax}<br>Total: ${s.total}</h3><p>Thank you for your business.</p></body></html>`}
function receiptHtml_(p,set){return`<html><body style="font-family:Arial;padding:28px"><h2>${esc_(set.shopName)}</h2><h3>Payment Receipt</h3><p>Date: ${p.date}<br>Received from: ${esc_(p.party)}<br>Type: ${p.type}<br>Mode: ${p.mode}<br>Reference: ${esc_(p.reference)}</p><h2>Amount: ${p.amount}</h2><p>${esc_(p.notes)}</p></body></html>`}
function requireRole_(u,rs){if(!rs.includes(u.role))throw new Error('Access denied.')}
function settings_(){const o={};getRows('Settings').forEach(x=>o[x.key]=x.value);return o}
function sheet_(n){return SpreadsheetApp.openById(SS_ID).getSheetByName(n)}
function getRows(n){const sh=sheet_(n);if(!sh||sh.getLastRow()<2)return[];return objects_(n)}
function objects_(n){const sh=sheet_(n),v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0];return v.slice(1).filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function appendRow(n,o){const h=SHEETS[n];sheet_(n).appendRow(h.map(k=>o[k]!==undefined?o[k]:''))}
function upsert_(n,o){const sh=sheet_(n),rows=getRows(n),i=rows.findIndex(x=>String(x.id||x.key)===String(o.id||o.key));if(i<0)appendRow(n,o);else sh.getRange(i+2,1,1,SHEETS[n].length).setValues([SHEETS[n].map(k=>o[k]!==undefined?o[k]:'')])}
function deleteById_(n,id,t){const u=auth_(t);requireRole_(u,['Administrator','Manager']);const rows=getRows(n),i=rows.findIndex(x=>String(x.id)===String(id));if(i<0)throw new Error('Record not found.');sheet_(n).deleteRow(i+2);return{ok:true}}
function audit_(u,a,e,id,d){appendRow('AuditLog',{id:uid(),timestamp:now_(),username:u.username,role:u.role,action:a,entity:e,entityId:id,details:d})}
function invoiceNo_(){const s=settings_();const p=s.invoicePrefix||'SSK';return p+'-'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd-HHmmss')}
function purchaseNo_(){return'PUR-'+Utilities.formatDate(new Date(),TZ,'yyyyMMdd-HHmmss')}
function uid(){return Utilities.getUuid()}function now_(){return Utilities.formatDate(new Date(),TZ,'yyyy-MM-dd HH:mm:ss')}function date_(){return Utilities.formatDate(new Date(),TZ,'yyyy-MM-dd')}function time_(){return Utilities.formatDate(new Date(),TZ,'HH:mm:ss')}function hash_(s){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8))}function sum_(a,k){return a.reduce((x,y)=>x+Number(y[k]||0),0)}function esc_(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
